{
 "title": "Proyectos Agile Copy",
 "description": "Una vista centralizada para obtener una visión general de los proyectos de desarrollo, con información de entrega efectiva, calidad y velocidad del mismo.",
 "time": { "from": "2023-02-09T06:02:29.096Z", "to": "2024-10-26T19:49:28.408Z" },
 "templating": {
  "list": [
   {
    "name": "proyecto",
    "label": "Proyecto",
    "query": "SELECT\n    CONCAT(\n        CASE\n            WHEN id = 'jira:JiraBoard:1:42' THEN 'OAUTH'\n            WHEN id = 'jira:JiraBoard:2:8' THEN 'VIVI'\n            WHEN id = 'jira:JiraBoard:3:147' THEN 'FRICTIONLESS'\n            WHEN id = 'jira:JiraBoard:4:81' THEN 'SUPERAPP'\n            WHEN id = 'jira:JiraBoard:5:64' THEN 'PASSWORD'\n\t\t\tWHEN id = 'jira:JiraBoard:6:139' THEN 'ZONA PUBLICA'\n\t\t\tWHEN id = 'jira:JiraBoard:6:138' THEN 'APP EMPRESAS'\n\t\t\tWHEN id = 'jira:JiraBoard:6:83' THEN 'MULTIBANCO'\n\t\t\tWHEN id = 'jira:JiraBoard:6:70' THEN 'CONSUMO PSE'\n        END,\n        '--',\n        id\n    ) AS response\nFROM boards\nWHERE id LIKE 'jira%'"
   },
   {
    "name": "sprint",
    "label": "Sprint",
    "query": "SELECT name\nFROM sprints\nWHERE original_board_id = '$proyecto'\n\nUNION ALL\n\nSELECT 'No hay resultados' AS name\nFROM (SELECT COUNT(*) AS cnt FROM sprints WHERE original_board_id = '$proyecto') AS sub\nWHERE sub.cnt = 0;"
   }
  ]
 },
 "panels": [
  {
   "title": "Productividad Insights",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<style type=\"text/css\">\n .css-15okvyg, .css-15okvyg {\n    background: linear-gradient(90deg, rgba(255,255,255,1) 0%, rgba(255,0,40,1) 25%, rgba(250,1,9,1) 50%, rgba(255,0,9,1) 75%, rgba(245,245,245,1) 100%) !important;\n  }\n  .css-dzzy4f {\n    background: red !important;\n  }\n  .css-1kficfj, .css-1p0t9ol-Icon, .css-fmaj2t-Icon{\n    color: white !important;\n  }\n\n  .css-1bht7sk a:hover, css-1bht7sk a:focus-visible {\n    color: white !important;\n    text-decoration: underline !important;\n  }\n\n  ol li .css-13q6pv9{\n    color: rgb(36, 41, 46) !important;\n  }\n\n  .css-13l8md7-panel-container {\n    box-shadow: 0px 0px 5px 0px rgba(0, 0, 0, 0.5) !important;\n  }\n\n  .css-13l8md7-panel-container {\n    border-radius: 15px;\n  }\n\n  .css-1ogk8cm::before {\n    background-image: linear-gradient(0.01deg, rgb(241 237 237) -31.2%, rgb(255 106 0) 113.07%) !important;  \n  }\n\n  .css-1ogk8cm {\n    background-color: rgb(170 52 52 / 30%);\n  }\n\n  button#mega-menu-toggle {\n    filter: brightness(0.5);\n  }\n  \n  button.css-xv13ed {\n    filter: brightness(0.5);\n  }\n\n  button.css-iobqob-toolbar-button-panel-header-state-button {\n    border-radius: 13px 0 0 0;\n  }\n</style>\n"
   }
  },
  {
   "title": "DETALLE SPRINT",
   "type": "table",
   "description": "Tabla que muestra la fecha de inicio y fin de los últimos 10 Sprint  creados en el proyecto",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 1 },
   "targets": [
    {
     "dataset": "`db-mysql-insights-dav-t-01`",
     "rawSql": "select name as Sprint, started_date as Fecha_Inicio, completed_date as Fecha_Fin FROM sprints\r\nwhere original_board_id = '${proyecto}'\r\nORDER BY completed_date DESC\r\nlimit 10"
    }
   ]
  },
  {
   "title": "DURACIÓN DEL SPRINT",
   "type": "stat",
   "description": "Duración del sprint en semanas ",
   "gridPos": { "h": 2, "w": 5, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT\r\n  CASE \r\n   WHEN DATEDIFF(ended_date, started_date) <= 8 THEN \"1 semana\"\r\n   WHEN DATEDIFF(ended_date, started_date) >= 8 THEN \"2 semanas\"\r\n   WHEN DATEDIFF(ended_date, started_date) > 15 and DATEDIFF(ended_date, started_date) <= 21  THEN \"3 semanas\"\r\n   ELSE NULL  \r\n  END AS resultado\r\nfrom sprints \r\nWHERE original_board_id = '${proyecto}'\r\nand status = 'ACTIVE'\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "TIEMPO DE VIDA DEL PROYECTO",
   "type": "stat",
   "description": "Duración total del proyecto en meses",
   "gridPos": { "h": 2, "w": 5, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT CONCAT(ROUND(DATEDIFF(max(ended_date), min(started_date)) / 30, 0), ' meses')\r\nFROM sprints WHERE original_board_id = '${proyecto}'"
    }
   ]
  },
  {
   "title": "PROYECTO",
   "type": "stat",
   "description": "Nombre general del proyecto ",
   "gridPos": { "h": 2, "w": 5, "x": 13, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT \r\n  CASE\r\n    WHEN id = 'jira:JiraBoard:1:42' THEN 'OAUTH'\r\n    WHEN id = 'jira:JiraBoard:2:8' THEN 'VIVI'\r\n    WHEN id = 'jira:JiraBoard:3:147' THEN 'FRICTIONLESS'\r\n    WHEN id = 'jira:JiraBoard:4:81' THEN 'SUPERAPP'\r\n    WHEN id = 'jira:JiraBoard:5:64' THEN 'PASSWORD'\r\n\t\tWHEN id = 'jira:JiraBoard:6:139' THEN 'ZONA PUBLICA'\r\n\t\tWHEN id = 'jira:JiraBoard:6:138' THEN 'APP EMPRESAS'\r\n\t\tWHEN id = 'jira:JiraBoard:6:83' THEN 'MULTIBANCO'\r\n\t\tWHEN id = 'jira:JiraBoard:6:70' THEN 'CONSUMO PSE'\r\n  END AS project\r\n  FROM boards\r\nWHERE id = '${proyecto}'"
    }
   ]
  },
  {
   "title": "NUMERO DE COLABORADORES",
   "type": "stat",
   "description": "Numero de personas que componen el equipo del proyecto\n",
   "gridPos": { "h": 2, "w": 5, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT\r\n  COUNT(DISTINCT i.assignee_name) AS total_Usuarios\r\nFROM\r\n  issues i\r\n  LEFT JOIN sprint_issues si ON i.id = si.issue_id\r\n  LEFT JOIN sprints s ON si.sprint_id = s.id\r\n  JOIN board_issues bi ON i.id = bi.issue_id\r\n  JOIN boards b ON bi.board_id = b.id\r\nWHERE\r\n\ti.type like '%HISTORIA%'\r\n\tand s.name in (${sprint})\r\n\tand b.id = '${proyecto}'\r\n\r\n"
    }
   ]
  },
  {
   "title": "CANTIDAD SPRINT PLANEADOS",
   "type": "stat",
   "description": "Numero de sprint realizados en el proyecto",
   "gridPos": { "h": 2, "w": 5, "x": 13, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT COUNT(DISTINCT(name)) \r\nFROM sprints\r\nWHERE original_board_id = '${proyecto}'"
    }
   ]
  },
  {
   "title": "Entrega Efectiva (HU: Historia de usuario)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }
  },
  {
   "title": "TENDENCIA DE ENTREGA HU (Durante todo el proyecto)",
   "type": "barchart",
   "description": "Grafica que muestra el número de historias cerradas por mes durante el proyecto\n ",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "WITH _requirements AS (\r\n  SELECT\r\n    DATE_ADD(DATE(i.created_date), INTERVAL -DAYOFMONTH(DATE(i.created_date)) + 1 DAY) AS time,\r\n    COUNT(DISTINCT CASE WHEN i.status = 'DONE' THEN i.id ELSE NULL END) AS Historias_completadas\r\n  FROM\r\n    issues i\r\n    JOIN board_issues bi ON i.id = bi.issue_id\r\n    JOIN boards b ON bi.board_id = b.id\r\n    JOIN board_sprints bs ON b.id = bs.board_id\r\n    JOIN sprints s ON bs.sprint_id = s.id  \r\n  WHERE\r\n    i.type like '%HISTORIA%'\r\n    AND bi.board_id = '${proyecto}'\r\n  GROUP BY 1\r\n)\r\n \r\nSELECT\r\n  time,\r\n  Historias_completadas\r\nFROM _requirements\r\nORDER BY time;"
    }
   ]
  },
  {
   "title": "HU COMPLETADAS",
   "type": "stat",
   "description": "Total de historias de usuario completadas en toda la ejecución o por sprint \n",
   "gridPos": { "h": 4, "w": 6, "x": 11, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT\r\n  COUNT(DISTINCT i.id)\r\nFROM\r\n  issues i\r\n  JOIN sprint_issues si on i.id = si.issue_id\r\n  JOIN sprints s ON si.sprint_id = s.id\r\n  JOIN board_issues bi on i.id = bi.issue_id\r\n  JOIN boards b on bi.board_id = b.id\r\nWHERE\r\n\ti.type like '%HISTORIA%'\r\n  and i.status = 'DONE'\r\n\tand s.name in (${sprint})\r\n\tand b.id = '${proyecto}'\r\n"
    }
   ]
  },
  {
   "title": "HU COMPROMETIDAS",
   "type": "stat",
   "description": "Total de historias de usuario comprometidas en toda la ejecución o por sprint \n",
   "gridPos": { "h": 4, "w": 6, "x": 17, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT\r\n  COUNT(DISTINCT i.id)\r\nFROM\r\n  issues i\r\n  JOIN sprint_issues si on i.id = si.issue_id\r\n  JOIN sprints s ON si.sprint_id = s.id\r\n  JOIN board_issues bi on i.id = bi.issue_id\r\n  JOIN boards b on bi.board_id = b.id\r\nWHERE\r\n\ti.type like '%HISTORIA%'\r\n\tand s.name in (${sprint})\r\n\tand b.id = '${proyecto}'\r\n\r\n"
    }
   ]
  },
  {
   "title": "PORCENTAJE DE CUMPLIMIENTO (HU)",
   "type": "stat",
   "description": "Promedio de Historias de usuario completadas en toda la ejecución del proyecto o por sprint\n",
   "gridPos": { "h": 5, "w": 6, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "WITH _requirements AS (\r\n    SELECT\r\n      COUNT(DISTINCT i.id) AS total_count,\r\n      COUNT(DISTINCT CASE WHEN i.status = 'DONE' THEN i.id ELSE NULL END) AS delivered_count\r\n    FROM\r\n      issues i\r\n      JOIN sprint_issues si on i.id = si.issue_id\r\n      JOIN sprints s ON si.sprint_id = s.id\r\n      JOIN board_issues bi on i.id = bi.issue_id\r\n      JOIN boards b on bi.board_id = b.id\r\n    WHERE\r\n      i.type like '%HISTORIA%'\r\n      and s.name in (${sprint})\r\n      and b.id = '${proyecto}'\r\n  )\r\n   \r\n  SELECT\r\n    NOW() AS time,\r\n    (delivered_count / total_count) * 100  AS requirement_delivery_rate_percentage\r\n  FROM _requirements"
    }
   ]
  },
  {
   "title": "LEAD TIME (DIAS)",
   "type": "stat",
   "description": "Tiempo promedio que le toma al equipo cerrar una historia de usuario ",
   "gridPos": { "h": 5, "w": 6, "x": 17, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "select\r\n  ROUND(AVG(lead_time_minutes / 1440), 0) AS value\r\nfrom\r\n    issues i\r\n    join board_issues bi on i.id = bi.issue_id\r\n    join boards b on bi.board_id = b.id\r\n    join board_sprints bs ON b.id = bs.board_id\r\n    join sprints s ON bs.sprint_id = s.id  \r\nwhere\r\n  i.type like '%HISTORIA%'\r\n  and i.status = 'DONE'\r\n  and bi.board_id = '${proyecto}'\r\n  and s.name in (${sprint})"
    }
   ]
  },
  {
   "title": "ESTADOS HU",
   "type": "piechart",
   "description": "Grafica que muestra el total de las historias por el estado en que se encuentran",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "with _iss as(\r\n  SELECT\r\n    i.status as estado,\r\n    COUNT(DISTINCT i.id) as cuenta\r\n  FROM\r\n    issues i\r\n    JOIN sprint_issues si on i.id = si.issue_id\r\n    JOIN sprints s ON si.sprint_id = s.id\r\n    JOIN board_issues bi on i.id = bi.issue_id\r\n    JOIN boards b on bi.board_id = b.id\r\n    WHERE\r\n      i.type like '%HISTORIA%'\r\n      and s.name in (${sprint})\r\n      and b.id = '${proyecto}'\r\n  GROUP BY 1\r\n)\r\nSELECT\r\n estado AS st,\r\n cuenta AS cu\r\nFROM _iss\r\nORDER by estado"
    }
   ]
  },
  {
   "title": "TIPO ISSUE",
   "type": "piechart",
   "description": "Grafica que muestra el total de las historias por tipo en el proyecto y sprints",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "with _iss as(\r\n  SELECT\r\n    i.type as tipo,\r\n    COUNT(DISTINCT i.id) as cuenta\r\n  FROM\r\n    issues i\r\n    JOIN sprint_issues si on i.id = si.issue_id\r\n    JOIN sprints s ON si.sprint_id = s.id\r\n    JOIN board_issues bi on i.id = bi.issue_id\r\n    JOIN boards b on bi.board_id = b.id\r\n    WHERE s.name in (${sprint})\r\n      and b.id = '${proyecto}'\r\n  GROUP BY 1\r\n)\r\nSELECT\r\n tipo AS st,\r\n cuenta AS cu\r\nFROM _iss\r\nORDER by tipo"
    }
   ]
  },
  {
   "title": "Entrega Efectiva (SP: Puntos de historia)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }
  },
  {
   "title": "TENDENCIA DE PUNTOS DE HISTORIA (Durante todo el proyecto)",
   "type": "barchart",
   "description": "Grafica que muestra la cantidad de puntos de historias completados por mes durante el proyecto\n ",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 27 },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "WITH _requirements AS (\r\n  SELECT\r\n    DATE_ADD(DATE(i.created_date), INTERVAL -DAYOFMONTH(DATE(i.created_date)) + 1 DAY) AS time,\r\n    SUM(DISTINCT CASE WHEN i.status = 'DONE' THEN i.story_point ELSE NULL END) AS Story_point_completados\r\n  FROM\r\n    issues i\r\n    JOIN board_issues bi ON i.id = bi.issue_id \r\n  WHERE\r\n    i.type like '%HISTORIA%'\r\n    AND bi.board_id = '${proyecto}'\r\n  GROUP BY 1\r\n)\r\n \r\nSELECT\r\n  time,\r\n  Story_point_completados\r\nFROM _requirements\r\nORDER BY time;"
    }
   ]
  },
  {
   "title": "PORCENTAJE DE CUMPLIMIENTO SP",
   "type": "stat",
   "description": "Promedio de puntos de historias completadas en toda la ejecución del proyecto o por sprint\n",
   "gridPos": { "h": 4, "w": 6, "x": 11, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "WITH _requirements AS (\r\n  SELECT\r\n    SUM(i.story_point) AS total_story_points,\r\n    SUM(CASE WHEN i.status = 'DONE' THEN i.story_point ELSE 0 END) AS done_story_points\r\n  FROM issues i\r\n  JOIN sprint_issues si on i.id = si.issue_id \r\n  JOIN sprints s ON si.sprint_id = s.id \r\n  JOIN board_issues bi ON i.id = bi.issue_id\r\n  join boards b on bi.board_id = b.id\r\n  WHERE\r\n    i.type like '%HISTORIA%'\r\n    AND s.name in (${sprint})\r\n    AND bi.board_id = '${proyecto}'\r\n)\r\n \r\nSELECT\r\n  NOW() AS time,\r\n  (done_story_points / total_story_points) * 100 AS done_story_points_percentage\r\nFROM _requirements;"
    }
   ]
  },
  {
   "title": "PUNTOS PROMEDIO POR (HU)",
   "type": "stat",
   "description": "Puntos de historias promedio por historia de usuario cerrados en todo el proyecto\n",
   "gridPos": { "h": 4, "w": 6, "x": 17, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "  SELECT\r\n   SUM(i.story_point) / COUNT(i.id) AS average_story_points_per_issue\r\nFROM\r\n  issues i\r\n  JOIN sprint_issues si ON i.id = si.issue_id\r\n  JOIN sprints s ON si.sprint_id = s.id\r\n  JOIN board_issues bi ON i.id = bi.issue_id\r\n  JOIN boards b ON bi.board_id = b.id\r\nWHERE\r\n  i.type like '%HISTORIA%'\r\n  AND s.name IN (${sprint})\r\n  AND b.id = '${proyecto}'\r\n"
    }
   ]
  },
  {
   "title": "SP COMPLETADOS",
   "type": "stat",
   "description": "Total de puntos de historias completadas en toda la ejecución o por sprint \n",
   "gridPos": { "h": 4, "w": 6, "x": 11, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT \r\n  SUM(i.story_point) AS total_story_points\r\nFROM \r\n  issues i\r\n  JOIN sprint_issues si on i.id = si.issue_id \r\n  JOIN sprints s ON si.sprint_id = s.id \r\n  JOIN board_issues bi on i.id = bi.issue_id\r\n  JOIN boards b on bi.board_id = b.id\r\nWHERE \r\n  i.type like '%HISTORIA%'\r\n  and i.status = 'DONE'\r\n  and s.name in (${sprint})\r\n  and b.id = '${proyecto}'"
    }
   ]
  },
  {
   "title": "SP COMPROMETIDOS",
   "type": "stat",
   "description": "Total de puntos de historias comprometidas en toda la ejecución o por sprint \n",
   "gridPos": { "h": 4, "w": 6, "x": 17, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT\r\n  SUM(i.story_point) AS total_story_points\r\nFROM\r\n  issues i\r\n  JOIN sprint_issues si on i.id = si.issue_id\r\n  JOIN sprints s ON si.sprint_id = s.id\r\n  join board_issues bi on i.id = bi.issue_id\r\n  join boards b on bi.board_id = b.id\r\nWHERE\r\n  i.type like '%HISTORIA%'\r\n  and s.name in (${sprint})\r\n  and b.id = '${proyecto}'"
    }
   ]
  },
  { "title": "Velocidad", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "CANTIDAD DE DESPLIEGUES POR AMBIENTE EN TODO EL PROYECTO",
   "type": "barchart",
   "description": "Numero de despliegues acumulados por ambiente  en toda la ejecución del proyecto\n",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 36 },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT\r\n  COUNT(DISTINCT cd.id) AS count, \r\n  CASE \r\n    WHEN UPPER(cd.environment) LIKE '%PR%' THEN 'PRODUCTION'\r\n\tWHEN UPPER(cd.environment) LIKE '%INT%' OR UPPER(cd.environment) LIKE '%DEV%' THEN 'INTEGRATION'\r\n\tWHEN UPPER(cd.environment) LIKE '%LAB%' THEN 'LABORATORY'\r\n\tELSE 'OTHERS'\r\n  END AS env\r\nFROM cicd_deployments cd\r\nJOIN cicd_deployment_commits cdc ON cd.id = cdc.cicd_deployment_id\r\nWHERE\r\n  cd.result = 'SUCCESS' AND \r\n  UPPER(cdc.repo_url) LIKE\r\n  CASE \r\n    WHEN '${proyecto:text}' = 'SUPERAPP' THEN '%DAVI-SAPP-%'\r\n    WHEN '${proyecto:text}' = 'FRICTIONLESS' THEN '%DAVI-FRL-%'\r\n    WHEN '${proyecto:text}' = 'PASSWORD' THEN '%DAVI-PWLS-%'\r\n    ELSE UPPER('%DAVI-${proyecto:text}-%')\r\n  END\r\nGROUP BY env"
    }
   ]
  },
  {
   "title": "TENDENCIA DE DESPLIEGUE POR AMBIENTE EN TODO EL PROYECTO",
   "type": "timeseries",
   "description": "Histórico de despliegues por ambiente en el tiempo de ejecución del proyecto o sprint\n",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "with _requirements as(\r\nSELECT \r\n  DATE_ADD(date(finished_date), INTERVAL -DAYOFMONTH(date(finished_date))+1 DAY) AS deployment_month,\r\n  1.0 * count(distinct case when environment IN ('lab', 'laboratory') then id else null end)/count(distinct id) as deployment_lab\r\nFROM \r\n  cicd_deployments\r\nWHERE\r\n UPPER(_raw_data_params) LIKE \r\n CASE \r\n    WHEN '${proyecto:text}' = 'SUPERAPP' THEN '%DAVI-SAPP-%'\r\n    WHEN '${proyecto:text}' = 'FRICTIONLESS' THEN '%DAVI-FRL-%'\r\n    WHEN '${proyecto:text}' = 'PASSWORD' THEN '%DAVI-PWLS-%'\r\n    ELSE UPPER('%DAVI-${proyecto:text}-%')\r\n  END\r\nGROUP BY 1\r\n) \r\nselect\r\n  deployment_month,\r\n  deployment_lab\r\nfrom _requirements\r\norder by deployment_month"
    },
    {
     "dataset": "lake",
     "rawSql": "with _requirements as(\r\nSELECT \r\n  DATE_ADD(date(finished_date), INTERVAL -DAYOFMONTH(date(finished_date))+1 DAY) AS deployment_month,\r\n  1.0 * count(distinct case when environment IN ('prd', 'production') then id else null end)/count(distinct id) as deployment_prd\r\nFROM \r\n  cicd_deployments\r\nWHERE\r\n UPPER(_raw_data_params) LIKE\r\n CASE \r\n    WHEN '${proyecto:text}' = 'SUPERAPP' THEN '%DAVI-SAPP-%'\r\n    WHEN '${proyecto:text}' = 'FRICTIONLESS' THEN '%DAVI-FRL-%'\r\n    WHEN '${proyecto:text}' = 'PASSWORD' THEN '%DAVI-PWLS-%'\r\n    ELSE UPPER('%DAVI-${proyecto:text}-%')\r\n  END\r\nGROUP BY 1\r\n) \r\nselect\r\n  deployment_month,\r\n  deployment_prd\r\nfrom _requirements\r\norder by deployment_month"
    },
    {
     "dataset": "lake",
     "rawSql": "with _requirements as(\r\nSELECT \r\n  DATE_ADD(date(finished_date), INTERVAL -DAYOFMONTH(date(finished_date))+1 DAY) AS deployment_month,\r\n  1.0 * count(distinct case when environment IN ('dev', 'integration') then id else null end)/count(distinct id) as deployment_dev\r\nFROM \r\n  cicd_deployments\r\nWHERE\r\n UPPER(_raw_data_params) LIKE\r\n CASE \r\n    WHEN '${proyecto:text}' = 'SUPERAPP' THEN '%DAVI-SAPP-%'\r\n    WHEN '${proyecto:text}' = 'FRICTIONLESS' THEN '%DAVI-FRL-%'\r\n    WHEN '${proyecto:text}' = 'PASSWORD' THEN '%DAVI-PWLS-%'\r\n    ELSE UPPER('%DAVI-${proyecto:text}-%')\r\n  END\r\nGROUP BY 1\r\n)\r\nselect\r\n  deployment_month,\r\n  deployment_dev\r\nfrom _requirements\r\norder by deployment_month"
    }
   ]
  },
  {
   "title": "FRECUENCIA DE DESPLIEGUE MENSUAL (PRODUCTION)",
   "type": "stat",
   "description": "Cantidad promedio de despliegues realizados en el ambiente de producción durante un mes.",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "deploy" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT \r\n    ROUND(AVG(deployment_count), 0) AS average_deployments_per_month\r\n  FROM (\r\n    SELECT \r\n      DATE_FORMAT(finished_date, '%Y-%m') AS deployment_month,\r\n      COUNT(*) AS deployment_count\r\n    FROM \r\n      cicd_deployments\r\n    WHERE \r\n      environment IN ('prd', 'production', 'PRODUCTION')\r\n      AND UPPER(_raw_data_params) LIKE\r\n      CASE \r\n        WHEN '${proyecto:text}' = 'SUPERAPP' THEN '%DAVI-SAPP-%'\r\n        WHEN '${proyecto:text}' = 'FRICTIONLESS' THEN '%DAVI-FRL-%'\r\n        WHEN '${proyecto:text}' = 'PASSWORD' THEN '%DAVI-PWLS-%'\r\n        ELSE UPPER('%DAVI-${proyecto:text}-%')\r\n      END\r\n      AND result = 'SUCCESS'\r\n    GROUP BY \r\n      DATE_FORMAT(finished_date, '%Y-%m')\r\n  ) AS monthly_deployments"
    }
   ]
  },
  {
   "title": "EFICIENCIA DE CAMBIOS (PRODUCTION)",
   "type": "stat",
   "description": "Mide la proporción de PRs cerrados (incluyendo los fusionados y los cerrados sin fusionar) respecto al total de PRs creados en el toda la ejecución del proyecto o sprint\n",
   "gridPos": { "h": 4, "w": 6, "x": 7, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "WITH pull_request_counts AS (\r\nSELECT\r\n    COUNT(DISTINCT pr.id) AS total_count,\r\n    COUNT(DISTINCT CASE WHEN pr.status IN ('MERGED') THEN pr.id ELSE NULL END) AS delivery_count\r\nFROM\r\n    pull_requests pr\r\nWHERE UPPER(url) LIKE\r\n CASE \r\n    WHEN '${proyecto:text}' = 'SUPERAPP' THEN '%DAVI-SAPP-%'\r\n    WHEN '${proyecto:text}' = 'FRICTIONLESS' THEN '%DAVI-FRL-%'\r\n    WHEN '${proyecto:text}' = 'PASSWORD' THEN '%DAVI-PWLS-%'\r\n    ELSE UPPER('%DAVI-${proyecto:text}-%')\r\n  END\r\n and base_ref in ('main')  \r\n    )\r\nSELECT\r\n    (delivery_count / total_count) * 100 AS open_pull_request_rate_percentage\r\nFROM\r\n    pull_request_counts"
    }
   ]
  },
  {
   "title": "TIEMPO MEDIO DE REVISION (HORAS)",
   "type": "stat",
   "description": "Permite ver el tiempo que le toma a una promoción de código la revisión de par para continua con la fusión en el siguiente ambiente\n",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "horas" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "select\r\n  AVG(TIMESTAMPDIFF(Minute,created_date,merged_date)/480)\r\nfrom\r\n    pull_requests\r\nwhere\r\n    merged_date is not null\r\n    and UPPER(url) LIKE\r\n    CASE \r\n      WHEN '${proyecto:text}' = 'SUPERAPP' THEN '%DAVI-SAPP-%'\r\n      WHEN '${proyecto:text}' = 'FRICTIONLESS' THEN '%DAVI-FRL-%'\r\n      WHEN '${proyecto:text}' = 'PASSWORD' THEN '%DAVI-PWLS-%'\r\n      ELSE UPPER('%DAVI-${proyecto:text}-%')\r\n    END\r\n    and base_ref in ('main', 'laboratory', 'integration');"
    }
   ]
  },
  {
   "title": "DESEMPEÑO",
   "type": "stat",
   "description": "Evaluación de desempeño de entrega en producción (ALTO si despliega mas de 4 veces por mes) (MEDIO si despliega al menos 1 vez al mes) y BAJO si el tiempo es mayor)",
   "gridPos": { "h": 16, "w": 4, "x": 19, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "deploy" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT \r\n  CASE\r\n    WHEN average_deployments_per_month >= 4 THEN 'Alto'\r\n    WHEN average_deployments_per_month >= 1 THEN 'Medio'\r\n    ELSE 'Bajo'\r\n  END AS deployment_rate\r\nFROM (\r\n  SELECT \r\n    AVG(deployment_count) AS average_deployments_per_month\r\n  FROM (\r\n    SELECT \r\n      DATE_FORMAT(finished_date, '%Y-%m') AS deployment_month,\r\n      COUNT(*) AS deployment_count\r\n    FROM \r\n      cicd_deployments\r\n    WHERE \r\n      environment IN ('prd','production')\r\n      AND finished_date >= DATE_SUB(CURRENT_DATE(), INTERVAL 2 YEAR)\r\n      AND UPPER(_raw_data_params) LIKE '%DAVI-${proyecto:text}-%'\r\n    GROUP BY \r\n      DATE_FORMAT(finished_date, '%Y-%m')\r\n  ) AS monthly_deployments\r\n) AS average_per_month;"
    }
   ]
  },
  {
   "title": "FRECUENCIA DE DESPLIEGUE MENSUAL (LABORATORY)",
   "type": "stat",
   "description": "Cantidad promedio de despliegues realizados en el ambiente de laboratorio durante un mes.",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "deploy" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT \r\n    ROUND(AVG(deployment_count), 0) AS average_deployments_per_month\r\n  FROM (\r\n    SELECT \r\n      DATE_FORMAT(finished_date, '%Y-%m') AS deployment_month,\r\n      COUNT(*) AS deployment_count\r\n    FROM \r\n      cicd_deployments\r\n    WHERE \r\n      environment IN ('lab', 'laboratory')\r\n      AND UPPER(_raw_data_params) LIKE\r\n      CASE \r\n        WHEN '${proyecto:text}' = 'SUPERAPP' THEN '%DAVI-SAPP-%'\r\n        WHEN '${proyecto:text}' = 'FRICTIONLESS' THEN '%DAVI-FRL-%'\r\n        WHEN '${proyecto:text}' = 'PASSWORD' THEN '%DAVI-PWLS-%'\r\n        ELSE UPPER('%DAVI-${proyecto:text}-%')\r\n      END\r\n      AND result = 'SUCCESS'\r\n    GROUP BY \r\n      DATE_FORMAT(finished_date, '%Y-%m')\r\n  ) AS monthly_deployments"
    }
   ]
  },
  {
   "title": "EFICIENCIA DE CAMBIOS (LABORATORY)",
   "type": "stat",
   "description": "Mide la proporción de PRs cerrados (incluyendo los fusionados y los cerrados sin fusionar) respecto al total de PRs creados en el toda la ejecución del proyecto o sprint\n",
   "gridPos": { "h": 4, "w": 6, "x": 7, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "WITH pull_request_counts AS (\r\nSELECT\r\n    COUNT(DISTINCT pr.id) AS total_count,\r\n    COUNT(DISTINCT CASE WHEN pr.status IN ('MERGED') THEN pr.id ELSE NULL END) AS delivery_count\r\nFROM\r\n    pull_requests pr\r\nWHERE UPPER(url) LIKE \r\n CASE \r\n    WHEN '${proyecto:text}' = 'SUPERAPP' THEN '%DAVI-SAPP-%'\r\n    WHEN '${proyecto:text}' = 'FRICTIONLESS' THEN '%DAVI-FRL-%'\r\n    WHEN '${proyecto:text}' = 'PASSWORD' THEN '%DAVI-PWLS-%'\r\n    ELSE UPPER('%DAVI-${proyecto:text}-%')\r\n  END\r\n and base_ref in ('lab', 'laboratory')    \r\n    )\r\nSELECT\r\n    (delivery_count / total_count) * 100 AS open_pull_request_rate_percentage\r\nFROM\r\n    pull_request_counts"
    }
   ]
  },
  {
   "title": "CYCLE TIME",
   "type": "stat",
   "description": "Tiempo que toma en completarse la historia de usuario, desde que se pone es estado de progres hasta su finalización o DONE.\n",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "horas" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT ROUND(AVG(T.tiempo_total), 0) FROM (\r\nSELECT\r\n  TIMESTAMPDIFF(DAY,i.created_date, i.resolution_date) as tiempo_total\r\nFROM  issues i\r\n  JOIN sprint_issues si on i.id = si.issue_id\r\n  JOIN sprints s ON si.sprint_id = s.id\r\n  JOIN board_issues bi on i.id = bi.issue_id\r\n  JOIN boards b on bi.board_id = b.id\r\nWHERE\r\n  i.type like '%HISTORIA%'\r\n  and i.status = 'DONE'\r\n  AND i.resolution_date is not null\r\n  and b.id = '${proyecto}'\r\nGROUP BY i.id) AS T"
    }
   ]
  },
  {
   "title": "FRECUENCIA DE DESPLIEGUE MENSUAL (INTEGRATION)",
   "type": "stat",
   "description": "Cantidad promedio de despliegues realizados en el ambiente de integración durante un mes.",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "deploy" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT \r\n    ROUND(AVG(deployment_count), 0) AS average_deployments_per_month\r\n  FROM (\r\n    SELECT \r\n      DATE_FORMAT(finished_date, '%Y-%m') AS deployment_month,\r\n      COUNT(*) AS deployment_count\r\n    FROM \r\n      cicd_deployments\r\n    WHERE \r\n      environment IN ('dev','integration')\r\n      AND result = 'SUCCESS'\r\n      AND UPPER(_raw_data_params) LIKE \r\n      CASE \r\n        WHEN '${proyecto:text}' = 'SUPERAPP' THEN '%DAVI-SAPP-%'\r\n        WHEN '${proyecto:text}' = 'FRICTIONLESS' THEN '%DAVI-FRL-%'\r\n        WHEN '${proyecto:text}' = 'PASSWORD' THEN '%DAVI-PWLS-%'\r\n        ELSE UPPER('%DAVI-${proyecto:text}-%')\r\n      END\r\n    GROUP BY \r\n      DATE_FORMAT(finished_date, '%Y-%m')\r\n  ) AS monthly_deployments"
    }
   ]
  },
  {
   "title": "EFICIENCIA DE CAMBIOS (INTEGRATION)",
   "type": "stat",
   "description": "Mide la proporción de PRs cerrados (incluyendo los fusionados y los cerrados sin fusionar) respecto al total de PRs creados en el toda la ejecución del proyecto o sprint\n",
   "gridPos": { "h": 4, "w": 6, "x": 7, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "WITH pull_request_counts AS (\r\nSELECT\r\n    COUNT(DISTINCT pr.id) AS total_count,\r\n    COUNT(DISTINCT CASE WHEN pr.status IN ('MERGED') THEN pr.id ELSE NULL END) AS delivery_count\r\nFROM\r\n    pull_requests pr\r\nWHERE UPPER(url) LIKE\r\n CASE \r\n    WHEN '${proyecto:text}' = 'SUPERAPP' THEN '%DAVI-SAPP-%'\r\n    WHEN '${proyecto:text}' = 'FRICTIONLESS' THEN '%DAVI-FRL-%'\r\n    WHEN '${proyecto:text}' = 'PASSWORD' THEN '%DAVI-PWLS-%'\r\n    ELSE UPPER('%DAVI-${proyecto:text}-%')\r\n  END\r\n and base_ref in ('integration', 'dev')\r\n    )\r\nSELECT\r\n    (delivery_count / total_count) * 100 AS open_pull_request_rate_percentage\r\nFROM\r\n    pull_request_counts"
    }
   ]
  },
  {
   "title": "BUGS",
   "type": "stat",
   "description": "Bugs son defectos en el código que podrían causar errores o comportamientos inesperados en el software. \n",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT count(distinct id) as 'Bugs'\r\nFROM cq_issues\r\nWHERE UPPER(project_key) LIKE\r\nCASE \r\n\tWHEN '${proyecto:text}' = 'SUPERAPP' THEN '%SAPP%'\r\n\tWHEN '${proyecto:text}' = 'FRICTIONLESS' THEN '%FRL%'\r\n\tWHEN '${proyecto:text}' = 'PASSWORD' THEN '%PWLS%'\r\n\tELSE '%${proyecto:text}%'\r\nEND\r\nAND type = 'BUG'"
    }
   ]
  },
  {
   "title": "VULNERABILIDADES",
   "type": "stat",
   "description": "Vulnerabilidades son debilidades en el código que pueden ser explotadas para comprometer la seguridad del software\n",
   "gridPos": { "h": 4, "w": 6, "x": 7, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT COUNT(distinct id) AS 'Vulnerabilities'\r\nFROM cq_issues\r\nWHERE UPPER(project_key) LIKE\r\nCASE \r\n\tWHEN '${proyecto:text}' = 'SUPERAPP' THEN '%SAPP%'\r\n\tWHEN '${proyecto:text}' = 'FRICTIONLESS' THEN '%FRL%'\r\n\tWHEN '${proyecto:text}' = 'PASSWORD' THEN '%PWLS%'\r\n\tELSE '%${proyecto:text}%'\r\nEND\r\nAND type = 'VULNERABILITY'\r\nAND status != 'CLOSED'"
    }
   ]
  },
  {
   "title": "GENERAL SMART COMMIT",
   "type": "stat",
   "description": "Porcentaje de Smart Commit realizados bajo los lineamientos (compara los realizados en github con los reportados en Jira.\n",
   "gridPos": { "h": 4, "w": 6, "x": 13, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT\r\n((SELECT COUNT(message) FROM commits\r\nWHERE (message LIKE '%${proyecto:text}-%' AND message LIKE '%fix%')\r\nOR (message LIKE '%${proyecto:text}-%' AND message LIKE '%feat%')\r\nOR (message LIKE '%${proyecto:text}-%' AND message LIKE '%build%')\r\nOR (message LIKE '%${proyecto:text}-%' AND message LIKE '%chore%')\r\nOR (message LIKE '%${proyecto:text}-%' AND message LIKE '%docs%')\r\nOR (message LIKE '%${proyecto:text}-%' AND message LIKE '%perf%')\r\nOR (message LIKE '%${proyecto:text}-%' AND message LIKE '%refactor%')\r\nOR (message LIKE '%${proyecto:text}-%' AND message LIKE '%revert%')\r\nOR (message LIKE '%${proyecto:text}-%' AND message LIKE '%style%')\r\n  OR (message LIKE '%${proyecto:text}-%' AND message LIKE '%test%')) * 100) /\r\n(SELECT COUNT(message) FROM commits)\r\nFROM commits\r\nLIMIT 1\r\n"
    }
   ]
  },
  { "title": "Calidad", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "VOLUMEN DE COBERTURA",
   "type": "stat",
   "description": "Este indicador mide la cantidad de líneas de código en el proyecto. Puede incluir tanto el código fuente como los comentarios y las líneas en blanco.\n",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT CONCAT(ROUND(sum(lines_to_cover) / 1000, 0),'k Lineas')\r\nFROM cq_file_metrics\r\nWHERE UPPER(project_key) LIKE\r\nCASE \r\n\tWHEN '${proyecto:text}' = 'SUPERAPP' THEN '%SAPP%'\r\n\tWHEN '${proyecto:text}' = 'FRICTIONLESS' THEN '%FRL%'\r\n\tWHEN '${proyecto:text}' = 'PASSWORD' THEN '%PWLS%'\r\n\tELSE '%${proyecto:text}%'\r\nEND"
    }
   ]
  },
  {
   "title": "SUGERENCIAS DE OPTIMIZACION",
   "type": "stat",
   "description": "Son recomendaciones proporcionadas por SonarQube para mejorar la eficiencia y la calidad del código\n",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT COUNT(distinct id) as 'Code Smells'\r\nFROM cq_issues\r\nWHERE UPPER(project_key) LIKE\r\nCASE \r\n\tWHEN '${proyecto:text}' = 'SUPERAPP' THEN '%SAPP%'\r\n\tWHEN '${proyecto:text}' = 'FRICTIONLESS' THEN '%FRL%'\r\n\tWHEN '${proyecto:text}' = 'PASSWORD' THEN '%PWLS%'\r\n\tELSE '%${proyecto:text}%'\r\nEND\r\nAND type = 'CODE_SMELL'"
    }
   ]
  },
  {
   "title": "GENERAL SONAR",
   "type": "stat",
   "description": "Evaluación total de sonar con los ponderados según los lineamientos (30% Cobertura de Pruebas) (30 %Code Smells)(30% Lineas Duplicadas)(10% (Busgs, Mantenibilidad, vulnerabilidades, seguridad, deuda)\n \n",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT\r\n((SELECT\r\n(SELECT ((ROUND((sum(lines_to_cover) - sum(uncovered_lines)) / sum(lines_to_cover) * 100, 1)-80) * 1.5) / 100 as valor\r\nFROM cq_file_metrics\r\nWHERE UPPER(project_key) LIKE\r\nCASE \r\n\tWHEN '${proyecto:text}' = 'SUPERAPP' THEN '%SAPP%'\r\n\tWHEN '${proyecto:text}' = 'FRICTIONLESS' THEN '%FRL%'\r\n\tWHEN '${proyecto:text}' = 'PASSWORD' THEN '%PWLS%'\r\n\tELSE '%${proyecto:text}%'\r\nEND) +\r\n(SELECT\r\n  (1 - ROUND(sum(duplicated_lines) / sum(num_of_lines) * 100, 1)) * 0.3 as lines_duplicated\r\nFROM cq_file_metrics\r\nWHERE UPPER(project_key) LIKE\r\nCASE \r\n\tWHEN '${proyecto:text}' = 'SUPERAPP' THEN '%SAPP%'\r\n\tWHEN '${proyecto:text}' = 'FRICTIONLESS' THEN '%FRL%'\r\n\tWHEN '${proyecto:text}' = 'PASSWORD' THEN '%PWLS%'\r\n\tELSE '%${proyecto:text}%'\r\nEND)\r\nFROM cq_file_metrics\r\nLIMIT 1) +\r\n(SELECT \r\n(SELECT  \r\n (CASE\r\n  WHEN COUNT(distinct id) = 0 THEN '100'\r\n  WHEN COUNT(distinct id) > 0 AND COUNT(distinct id) <= 10 THEN '90'\r\n  WHEN COUNT(distinct id) > 10 AND COUNT(distinct id) <= 20 THEN '80'\r\n  WHEN COUNT(distinct id) > 20 AND COUNT(distinct id) <= 40 THEN '60'\r\n  WHEN COUNT(distinct id) > 40 AND COUNT(distinct id) <= 60 THEN '40'\r\n  WHEN COUNT(distinct id) > 60 AND COUNT(distinct id) <= 80 THEN '20'\r\n  WHEN COUNT(distinct id) > 80 THEN '0'\r\n  END) * 0.3 / 100 as 'Code Smells'\r\nFROM cq_issues\r\nWHERE UPPER(project_key) LIKE\r\nCASE \r\n\tWHEN '${proyecto:text}' = 'SUPERAPP' THEN '%SAPP%'\r\n\tWHEN '${proyecto:text}' = 'FRICTIONLESS' THEN '%FRL%'\r\n\tWHEN '${proyecto:text}' = 'PASSWORD' THEN '%PWLS%'\r\n\tELSE '%${proyecto:text}%'\r\nEND\r\nAND type = 'CODE_SMELL') +\r\n(SELECT case WHEN COUNT(distinct id) = 0 THEN '0.025' ELSE '0'\r\nend as vulnerability\r\nFROM cq_issues\r\nWHERE UPPER(project_key) LIKE\r\nCASE \r\n\tWHEN '${proyecto:text}' = 'SUPERAPP' THEN '%SAPP%'\r\n\tWHEN '${proyecto:text}' = 'FRICTIONLESS' THEN '%FRL%'\r\n\tWHEN '${proyecto:text}' = 'PASSWORD' THEN '%PWLS%'\r\n\tELSE '%${proyecto:text}%'\r\nEND\r\n AND type = 'VULNERABILITY'\r\n AND status != 'CLOSED') +\r\n(SELECT case WHEN COUNT(distinct id) = 0 THEN '0.05' ELSE '0'\r\nend as bug\r\nFROM cq_issues\r\nWHERE UPPER(project_key) LIKE\r\nCASE \r\n\tWHEN '${proyecto:text}' = 'SUPERAPP' THEN '%SAPP%'\r\n\tWHEN '${proyecto:text}' = 'FRICTIONLESS' THEN '%FRL%'\r\n\tWHEN '${proyecto:text}' = 'PASSWORD' THEN '%PWLS%'\r\n\tELSE '%${proyecto:text}%'\r\nEND\r\n AND type = 'BUG'\r\n AND status != 'CLOSED') +\r\n(SELECT case WHEN COUNT(distinct id) = 0 THEN '0.025' ELSE '0'\r\nend as hotspots\r\nFROM cq_issues\r\nWHERE UPPER(project_key) LIKE\r\nCASE \r\n\tWHEN '${proyecto:text}' = 'SUPERAPP' THEN '%SAPP%'\r\n\tWHEN '${proyecto:text}' = 'FRICTIONLESS' THEN '%FRL%'\r\n\tWHEN '${proyecto:text}' = 'PASSWORD' THEN '%PWLS%'\r\n\tELSE '%${proyecto:text}%'\r\nEND\r\n\t  AND type = 'HOTSPOTS'\r\n    AND status != 'CLOSED'\r\n    )\r\n\t  FROM (select DISTINCT(id) from cq_issues) as sumatoria\r\n LIMIT 1)) * 100 AS indicador_calidad\r\n FROM cq_issues ci JOIN cq_file_metrics cfm ON ci.project_key = cfm.project_key\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "GENERAL CALIDAD",
   "type": "stat",
   "description": "Calificación total del proyecto segun el indicador (80% de general sonar y 20 % de smart Commit)\n",
   "gridPos": { "h": 8, "w": 6, "x": 17, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT(\r\nSELECT(\r\n(SELECT\r\n(SELECT ((ROUND((sum(lines_to_cover) - sum(uncovered_lines)) / sum(lines_to_cover) * 100, 1)-80) * 1.5) / 100 as valor\r\nFROM cq_file_metrics\r\nWHERE UPPER(project_key) LIKE\r\nCASE \r\n\tWHEN '${proyecto:text}' = 'SUPERAPP' THEN '%SAPP%'\r\n\tWHEN '${proyecto:text}' = 'FRICTIONLESS' THEN '%FRL%'\r\n\tWHEN '${proyecto:text}' = 'PASSWORD' THEN '%PWLS%'\r\n\tELSE '%${proyecto:text}%'\r\nEND) +\r\n(SELECT\r\n  (1 - ROUND(sum(duplicated_lines) / sum(num_of_lines) * 100, 1)) * 0.3 as lines_duplicated\r\nFROM cq_file_metrics\r\nWHERE UPPER(project_key) LIKE\r\nCASE \r\n\tWHEN '${proyecto:text}' = 'SUPERAPP' THEN '%SAPP%'\r\n\tWHEN '${proyecto:text}' = 'FRICTIONLESS' THEN '%FRL%'\r\n\tWHEN '${proyecto:text}' = 'PASSWORD' THEN '%PWLS%'\r\n\tELSE '%${proyecto:text}%'\r\nEND)\r\nFROM cq_file_metrics\r\nLIMIT 1) +\r\n(SELECT\r\n(SELECT  \r\n (CASE\r\n  WHEN COUNT(distinct id) = 0 THEN '100'\r\n  WHEN COUNT(distinct id) > 0 AND COUNT(distinct id) <= 10 THEN '90'\r\n  WHEN COUNT(distinct id) > 10 AND COUNT(distinct id) <= 20 THEN '80'\r\n  WHEN COUNT(distinct id) > 20 AND COUNT(distinct id) <= 40 THEN '60'\r\n  WHEN COUNT(distinct id) > 40 AND COUNT(distinct id) <= 60 THEN '40'\r\n  WHEN COUNT(distinct id) > 60 AND COUNT(distinct id) <= 80 THEN '20'\r\n  WHEN COUNT(distinct id) > 80 THEN '0'\r\n  END) * 0.3 / 100 as 'Code Smells'\r\nFROM cq_issues\r\nWHERE UPPER(project_key) LIKE\r\nCASE \r\n\tWHEN '${proyecto:text}' = 'SUPERAPP' THEN '%SAPP%'\r\n\tWHEN '${proyecto:text}' = 'FRICTIONLESS' THEN '%FRL%'\r\n\tWHEN '${proyecto:text}' = 'PASSWORD' THEN '%PWLS%'\r\n\tELSE '%${proyecto:text}%'\r\nEND\r\nAND type = 'CODE_SMELL') +\r\n(SELECT case WHEN COUNT(distinct id) = 0 THEN '0.025' ELSE '0'\r\nend as vulnerability\r\nFROM cq_issues\r\nWHERE UPPER(project_key) LIKE\r\nCASE \r\n\tWHEN '${proyecto:text}' = 'SUPERAPP' THEN '%SAPP%'\r\n\tWHEN '${proyecto:text}' = 'FRICTIONLESS' THEN '%FRL%'\r\n\tWHEN '${proyecto:text}' = 'PASSWORD' THEN '%PWLS%'\r\n\tELSE '%${proyecto:text}%'\r\nEND\r\n AND type = 'VULNERABILITY'\r\n AND status != 'CLOSED') +\r\n(SELECT case WHEN COUNT(distinct id) = 0 THEN '0.05' ELSE '0'\r\nend as bug\r\nFROM cq_issues\r\nWHERE UPPER(project_key) LIKE\r\nCASE \r\n\tWHEN '${proyecto:text}' = 'SUPERAPP' THEN '%SAPP%'\r\n\tWHEN '${proyecto:text}' = 'FRICTIONLESS' THEN '%FRL%'\r\n\tWHEN '${proyecto:text}' = 'PASSWORD' THEN '%PWLS%'\r\n\tELSE '%${proyecto:text}%'\r\nEND\r\n AND type = 'BUG'\r\n AND status != 'CLOSED') +\r\n(SELECT case WHEN COUNT(distinct id) = 0 THEN '0.025' ELSE '0'\r\nend as hotspots\r\nFROM cq_issues\r\nWHERE UPPER(project_key) LIKE\r\nCASE \r\n\tWHEN '${proyecto:text}' = 'SUPERAPP' THEN '%SAPP%'\r\n\tWHEN '${proyecto:text}' = 'FRICTIONLESS' THEN '%FRL%'\r\n\tWHEN '${proyecto:text}' = 'PASSWORD' THEN '%PWLS%'\r\n\tELSE '%${proyecto:text}%'\r\nEND\r\n    AND type = 'HOTSPOTS'\r\n    AND status != 'CLOSED')\r\n    FROM (select DISTINCT(id) from cq_issues) as sumatoria\r\n LIMIT 1)) * 80 AS indicador_calidad\r\n FROM cq_issues ci JOIN cq_file_metrics cfm ON ci.project_key = cfm.project_key\r\nLIMIT 1)\r\n+\r\n(SELECT\r\n(((SELECT COUNT(message) FROM commits\r\nWHERE (message LIKE '%${proyecto:text}-%' AND message LIKE '%fix%')\r\nOR (message LIKE '%${proyecto:text}-%' AND message LIKE '%feat%')\r\nOR (message LIKE '%${proyecto:text}-%' AND message LIKE '%build%')\r\nOR (message LIKE '%${proyecto:text}-%' AND message LIKE '%chore%')\r\nOR (message LIKE '%${proyecto:text}-%' AND message LIKE '%docs%')\r\nOR (message LIKE '%${proyecto:text}-%' AND message LIKE '%perf%')\r\nOR (message LIKE '%${proyecto:text}-%' AND message LIKE '%refactor%')\r\nOR (message LIKE '%${proyecto:text}-%' AND message LIKE '%revert%')\r\nOR (message LIKE '%${proyecto:text}-%' AND message LIKE '%style%')\r\n  OR (message LIKE '%${proyecto:text}-%' AND message LIKE '%test%')) * 100) /\r\n(SELECT COUNT(message) FROM commits)) * 0.2\r\nFROM commits\r\nLIMIT 1) AS total"
    }
   ]
  },
  {
   "title": "DEUDA TECNICA",
   "type": "stat",
   "description": "representa el costo estimado del trabajo adicional necesario para corregir los problemas de calidad en el código\n",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT \r\n  IFNULL(\r\n    CONCAT(\r\n      FLOOR(SUM(debt) / 8 / 60), \r\n      ' day(s) ', \r\n      FLOOR((SUM(debt) % 480) / 60), \r\n      ' hour(s)'\r\n    ), \r\n    'Sin deuda'\r\n  ) AS Debt\r\nFROM cq_issues\r\nWHERE UPPER(project_key) LIKE\r\nCASE \r\n\tWHEN '${proyecto:text}' = 'SUPERAPP' THEN '%SAPP%'\r\n\tWHEN '${proyecto:text}' = 'FRICTIONLESS' THEN '%FRL%'\r\n\tWHEN '${proyecto:text}' = 'PASSWORD' THEN '%PWLS%'\r\n\tELSE '%${proyecto:text}%'\r\nEND\r\nAND status != 'CLOSED';"
    }
   ]
  },
  {
   "title": "COBERTURA DE PRUEBAS",
   "type": "stat",
   "description": "mide el porcentaje de código que está cubierto por pruebas unitarias\n",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT CONCAT(ROUND((sum(lines_to_cover) - sum(uncovered_lines)) / sum(lines_to_cover) * 100, 1), '% ')\r\nFROM cq_file_metrics\r\nWHERE UPPER(project_key) LIKE\r\nCASE \r\n\tWHEN '${proyecto:text}' = 'SUPERAPP' THEN '%SAPP%'\r\n\tWHEN '${proyecto:text}' = 'FRICTIONLESS' THEN '%FRL%'\r\n\tWHEN '${proyecto:text}' = 'PASSWORD' THEN '%PWLS%'\r\n\tELSE '%${proyecto:text}%'\r\nEND"
    }
   ]
  },
  { "title": "Testing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "NUMERO DE TEST EXECUTION",
   "type": "stat",
   "description": "Total de historias de tipo Test Execution en toda la ejecución o por sprint",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "`db-mysql-insights-dav-t-01`",
     "rawSql": "SELECT\r\n  COUNT(DISTINCT i.id)\r\nFROM\r\n  issues i\r\n  JOIN sprint_issues si on i.id = si.issue_id\r\n  JOIN sprints s ON si.sprint_id = s.id\r\n  JOIN board_issues bi on i.id = bi.issue_id\r\n  JOIN boards b on bi.board_id = b.id\r\nWHERE\r\n\ti.type like 'TEST EXECUTION'\r\n\tand s.name in (${sprint})\r\n\tand b.id = '${proyecto}'"
    }
   ]
  },
  {
   "title": "ESTADO DE TEST EXECUTION",
   "type": "piechart",
   "description": "Gráfica que muestra el estado de los test execution por proyecto o por sprint",
   "gridPos": { "h": 5, "w": 6, "x": 3, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "with _iss as(\r\n  SELECT\r\n    i.status as estado,\r\n    COUNT(DISTINCT i.id) as cuenta\r\n  FROM\r\n    issues i\r\n    JOIN sprint_issues si on i.id = si.issue_id\r\n    JOIN sprints s ON si.sprint_id = s.id\r\n    JOIN board_issues bi on i.id = bi.issue_id\r\n    JOIN boards b on bi.board_id = b.id\r\n    WHERE\r\n      i.type like 'TEST EXECUTION'\r\n      and s.name in (${sprint})\r\n      and b.id = '${proyecto}'\r\n  GROUP BY 1\r\n)\r\nSELECT\r\n estado AS st,\r\n cuenta AS cu\r\nFROM _iss\r\nORDER by estado"
    }
   ]
  },
  {
   "title": "TEST SATISFACTORIOS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "`db-mysql-insights-dav-t-01`",
     "rawSql": "SELECT test_Status as Estado_del_Test, count(distinct id_test) as Cantidad_de_Tests\r\nFROM xray_testExecutions\r\nwhere test_Status = 'PASSED'\r\nGROUP BY test_Status"
    }
   ]
  },
  {
   "title": "CANTIDAD DE ESTADOS  DE TEST",
   "type": "table",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 70 },
   "targets": [
    {
     "dataset": "`db-mysql-insights-dav-t-01`",
     "rawSql": "SELECT test_Status as Estado_del_Test, count(distinct id_test) as Cantidad_de_Tests\r\nFROM xray_testExecutions\r\nGROUP BY test_Status"
    }
   ]
  },
  {
   "title": "EFECTIVIDAD",
   "type": "stat",
   "description": "\n",
   "gridPos": { "h": 15, "w": 5, "x": 18, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT \r\n    COUNT(*) AS total_tests,\r\n    SUM(CASE WHEN test_Status = 'PASSED' THEN 1 ELSE 0 END) AS satisfactory_tests,\r\n    (SUM(CASE WHEN test_Status = 'PASSED' THEN 1 ELSE 0 END) * 100.0 / COUNT(*)) AS percentage\r\nFROM \r\n    xray_testExecutions;"
    }
   ]
  },
  {
   "title": "NUMERO DE TEST",
   "type": "stat",
   "description": "Total de historias de tipo Test en toda la ejecución o por sprint",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 75 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "`db-mysql-insights-dav-t-01`",
     "rawSql": "SELECT\r\n  COUNT(DISTINCT i.id)\r\nFROM\r\n  issues i\r\n  JOIN sprint_issues si on i.id = si.issue_id\r\n  JOIN sprints s ON si.sprint_id = s.id\r\n  JOIN board_issues bi on i.id = bi.issue_id\r\n  JOIN boards b on bi.board_id = b.id\r\nWHERE\r\n\ti.type like 'TEST'\r\n\tand s.name in (${sprint})\r\n\tand b.id = '${proyecto}'"
    }
   ]
  },
  {
   "title": "ESTADO DE TEST",
   "type": "piechart",
   "description": "Gráfica que muestra el estado de los test por proyecto o por sprint",
   "gridPos": { "h": 5, "w": 6, "x": 3, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "with _iss as(\r\n  SELECT\r\n    i.status as estado,\r\n    COUNT(DISTINCT i.id) as cuenta\r\n  FROM\r\n    issues i\r\n    JOIN sprint_issues si on i.id = si.issue_id\r\n    JOIN sprints s ON si.sprint_id = s.id\r\n    JOIN board_issues bi on i.id = bi.issue_id\r\n    JOIN boards b on bi.board_id = b.id\r\n    WHERE\r\n      i.type like 'TEST'\r\n      and s.name in (${sprint})\r\n      and b.id = '${proyecto}'\r\n  GROUP BY 1\r\n)\r\nSELECT\r\n estado AS st,\r\n cuenta AS cu\r\nFROM _iss\r\nORDER by estado"
    }
   ]
  },
  {
   "title": "COLABORADORES ASIGNADOS",
   "type": "stat",
   "description": "Número de personas asignadas a los test del proyecto",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 75 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "`db-mysql-insights-dav-t-01`",
     "rawSql": "SELECT\r\n  COUNT(DISTINCT i.assignee_name) AS total_Usuarios\r\nFROM\r\n  issues i\r\n  JOIN sprint_issues si ON i.id = si.issue_id\r\n  JOIN sprints s ON si.sprint_id = s.id\r\n  JOIN board_issues bi ON i.id = bi.issue_id\r\n  JOIN boards b ON bi.board_id = b.id\r\nWHERE\r\n   i.type like 'TEST'\r\n  AND b.id = '${proyecto}'"
    }
   ]
  },
  {
   "title": "TESTER ASIGNADOS",
   "type": "table",
   "description": "Nombre de las personas asignadas a los test del proyecto",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 75 },
   "targets": [
    {
     "dataset": "`db-mysql-insights-dav-t-01`",
     "rawSql": "SELECT DISTINCT i.assignee_name\r\nFROM issues i\r\n  JOIN board_issues bi on i.id = bi.issue_id\r\n  JOIN boards b on bi.board_id = b.id\r\nWHERE \r\n  i.type LIKE 'TEST'\r\n  and i.assignee_name != ''\r\n  and b.id = '${proyecto}'"
    }
   ]
  },
  {
   "title": "CANTIDAD DE TIPO DE TEST",
   "type": "table",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 80 },
   "targets": [
    {
     "dataset": "`db-mysql-insights-dav-t-01`",
     "rawSql": "SELECT test_Type as Tipo_de_Test, count(distinct id_test) as Cantidad_de_Tests\r\nFROM xray_testExecutions\r\nGROUP BY Tipo_de_Test"
    }
   ]
  },
  {
   "title": "PRIORIDAD",
   "type": "stat",
   "description": "Prioridad de la historia de tipo Test",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT i.type, i.priority\r\nFROM issues i\r\n  JOIN board_issues bi on i.id = bi.issue_id\r\n  JOIN boards b on bi.board_id = b.id\r\nWHERE \r\n  i.type LIKE 'TEST'\r\n  and b.id = '${proyecto}'"
    }
   ]
  },
  {
   "title": "TIPO DE TEST",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 80 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "`db-mysql-insights-dav-t-01`",
     "rawSql": "SELECT test_Type\r\nFROM xray_testExecutions"
    }
   ]
  },
  { "title": "Seguridad", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "ESTADO DEL ANÁLISIS",
   "type": "piechart",
   "description": "Gráfica que muestra el estado del escaneo de los repositorios del proyecto",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT policy, count(policy)\r\nFROM vc_applications_test\r\nWHERE UPPER(profileName) LIKE\r\nCASE \r\n\tWHEN '${proyecto:text}' = 'SUPERAPP' THEN '%DAVI-SAPP-%'\r\n\tWHEN '${proyecto:text}' = 'FRICTIONLESS' THEN '%DAVI-FRL-%'\r\n\tWHEN '${proyecto:text}' = 'PASSWORD' THEN '%DAVI-PWLS-%'\r\n\tELSE UPPER('%DAVI-${proyecto:text}-%')\r\nEND\r\nGROUP BY  policy"
    }
   ]
  },
  {
   "title": "CANTIDAD RESPOSITORIOS",
   "type": "stat",
   "description": "Número de repositorios que cuentan con un escaneo de seguridad en el proyecto.",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 86 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "`db-mysql-insights-dav-t-01`",
     "rawSql": "SELECT COUNT(distinct(profileName)) as Repository\r\nFROM vc_applications_test\r\nWHERE UPPER(profileName) LIKE\r\nCASE \r\n\tWHEN '${proyecto:text}' = 'SUPERAPP' THEN '%DAVI-SAPP-%'\r\n\tWHEN '${proyecto:text}' = 'FRICTIONLESS' THEN '%DAVI-FRL-%'\r\n\tWHEN '${proyecto:text}' = 'PASSWORD' THEN '%DAVI-PWLS-%'\r\n\tELSE UPPER('%DAVI-${proyecto:text}-%')\r\nEND"
    }
   ]
  },
  {
   "title": "CRITICIDAD",
   "type": "stat",
   "description": "Very High: Aplicaciones críticas para la misión del negocio o la seguridad de vida y salud.\nHigh: Aplicaciones importantes que, si se ven comprometidas, podrían afectar seriamente algunas funciones clave del negocio, pero no de manera catastrófica.\nMedium: Aplicaciones que, si se ven comprometidas, podrían causar molestias o afectar parcialmente las operaciones, pero sin un impacto mayor.\nLow: Aplicaciones que tienen un impacto mínimo en el negocio; su compromiso no sería crítico y podría ser manejado con poca interrupción.\nVery Low: Aplicaciones que son de baja importancia para el negocio, con un impacto casi nulo si son comprometidas.",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT distinct(businessCriticality)\r\nFROM vc_applications_test\r\nWHERE UPPER(profileName) LIKE\r\nCASE \r\n\tWHEN '${proyecto:text}' = 'SUPERAPP' THEN '%DAVI-SAPP-%'\r\n\tWHEN '${proyecto:text}' = 'FRICTIONLESS' THEN '%DAVI-FRL-%'\r\n\tWHEN '${proyecto:text}' = 'PASSWORD' THEN '%DAVI-PWLS-%'\r\n\tELSE UPPER('%DAVI-${proyecto:text}-%')\r\nEND"
    }
   ]
  },
  {
   "title": "TIPO DE ESCANEO",
   "type": "stat",
   "description": "Tipo de análisis de seguridad que se realiza sobre los repositorios del proyecto.",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 86 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "`db-mysql-insights-dav-t-01`",
     "rawSql": "SELECT distinct(scanType)\r\nFROM vc_applications_test\r\nWHERE UPPER(profileName) LIKE\r\nCASE \r\n\tWHEN '${proyecto:text}' = 'SUPERAPP' THEN '%DAVI-SAPP-%'\r\n\tWHEN '${proyecto:text}' = 'FRICTIONLESS' THEN '%DAVI-FRL-%'\r\n\tWHEN '${proyecto:text}' = 'PASSWORD' THEN '%DAVI-PWLS-%'\r\n\tELSE UPPER('%DAVI-${proyecto:text}-%')\r\nEND"
    }
   ]
  },
  {
   "title": "GENERAL SEGURIDAD",
   "type": "stat",
   "description": "\n",
   "gridPos": { "h": 10, "w": 5, "x": 18, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT SUM(score) AS Score\r\nFROM vc_flaws_test\r\nWHERE UPPER(flawPath) LIKE\r\nCASE \r\n\tWHEN '${proyecto:text}' = 'SUPERAPP' THEN '%SAPP%'\r\n\tWHEN '${proyecto:text}' = 'FRICTIONLESS' THEN '%FRL%'\r\n\tWHEN '${proyecto:text}' = 'PASSWORD' THEN '%PWLS%'\r\n\tELSE '%${proyecto:text}%'\r\nEND;"
    }
   ]
  },
  {
   "title": "RESULTADO ESCANEO",
   "type": "table",
   "description": "Resultado del escaneo por criticidad",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 91 },
   "targets": [
    {
     "dataset": "`db-mysql-insights-dav-t-01`",
     "rawSql": "SELECT severityCVE AS Severity, AVG(score) AS Score\r\nFROM vc_flaws_test\r\nWHERE UPPER(flawPath) LIKE\r\nCASE \r\n\tWHEN '${proyecto:text}' = 'SUPERAPP' THEN '%SAPP%'\r\n\tWHEN '${proyecto:text}' = 'FRICTIONLESS' THEN '%FRL%'\r\n\tWHEN '${proyecto:text}' = 'PASSWORD' THEN '%PWLS%'\r\n\tELSE '%${proyecto:text}%'\r\nEND\r\nGROUP BY severityCVE;"
    }
   ]
  },
  {
   "title": "LENGUAJE",
   "type": "stat",
   "description": "Lenguaje en el que esta escrito el código del proyecto.",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 91 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "`db-mysql-insights-dav-t-01`",
     "rawSql": "SELECT distinct(language)\r\nFROM vc_flaws_test\r\nWHERE UPPER(flawPath) LIKE\r\nCASE \r\n\tWHEN '${proyecto:text}' = 'SUPERAPP' THEN '%SAPP%'\r\n\tWHEN '${proyecto:text}' = 'FRICTIONLESS' THEN '%FRL%'\r\n\tWHEN '${proyecto:text}' = 'PASSWORD' THEN '%PWLS%'\r\n\tELSE '%${proyecto:text}%'\r\nEND\r\n"
    }
   ]
  },
  {
   "title": "UNIDAD DE NEGOCIO",
   "type": "stat",
   "description": "Unidad de negocio a la que pertenece el proyecto",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 91 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "`db-mysql-insights-dav-t-01`",
     "rawSql": "SELECT distinct(businessUnitName)\r\nFROM vc_applications_test\r\nWHERE UPPER(profileName) LIKE\r\nCASE \r\n\tWHEN '${proyecto:text}' = 'SUPERAPP' THEN '%SAPP%'\r\n\tWHEN '${proyecto:text}' = 'FRICTIONLESS' THEN '%FRL%'\r\n\tWHEN '${proyecto:text}' = 'PASSWORD' THEN '%PWLS%'\r\n\tELSE '%${proyecto:text}%'\r\nEND\r\nLIMIT 1"
    }
   ]
  }
 ]
}